apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-auth-secret
  namespace: grafana
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    grafana-password: AgA731x5vdBqNoCAGs3m6OUgg+i9HaixR6D4ngbCkira3CP7hMo2z/+ULgPECrl4GX2Yu1mFrj2i5fFeigTejt/6UxuHYFaM79ud41qmjZ7vKgbBzxeqQz1EaqlsQ+ONsAlW1pOPYAAc7xQTExfLvmZZFja35gurJcfSO5YEa7G2w7n22/dBzpqMhkDGCkBbD1XnoWCELPO5tEdZVfnN4rXUZ8EPiDMiYrCHF72IjIuxVm1YRto8y6VStwg1oyqJU9T1MPiuSGg2XPQDYGmhfR5WrzqTC+ZZUGKNnEFxDlpAUj7shjTL6GJGH1rB0xd+U1lzpGkKRVt0jhjl9o9Tz61Fk3BcZRSi43euqjTDOi4SiAFJo/eUbsAcAJUGvMlyO63twrRIFsfr7uY+kaXBJ8PPuT0HIgY5UJkYK/ayaCQ34mlPfpt8qq6FcvNAcsZGsOcSSG8IqSL2umrUytfQpxL7KgTkHv/14+feNBkXpQe6BU1k2fgoL/44dBxs454fk/YOcw5tmReTuOL5pQCvgqemOdyuFo1nGNP2GEDUnP5nYKMlb9ajciZWb2zjjwLCsWsXXzuz0QHdOshNaqoPVNxmoXYSEGQf4H3WZKCYipst1PTA6A+IJ+EW2VSUFj8sKSSZTspRz/gKPVGjuCxyO4pyDggYsrEpvl/CDQZfnV/2B+17CxVeGQlZoBqnZdCantsqD7h5PdwHcoAgng==
  template:
    type: Opaque
