apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: grafana-auth-secret
  data:
  - secretKey: grafana-password
    remoteRef:
      key: /monitoring/grafana/grafana-auth-secret/grafana-password
      version: v1
