apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: grafana-auth-secret
  data:
  - secretKey: grafana-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 3e94548e-f7be-4fcc-a50c-b2bc010b706f
      version: v1
