nifi:
  image:
    registry: docker.io
    repository: apache/nifi
    tag: "1.27.0"

  replicaCount: 3

  containerPorts:
    cluster: 6007
    siteToSite: 10000
    metrics: 9092

  resources: {}

  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000

  service:
    type: ClusterIP
    ports:
      cluster: 6007
      siteToSite: 10000
      metrics: 9092

  serviceAccount:
    create: true

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  ingress:
    # Use cloudflare tunnel instead
    enabled: false

  tls:
    certManager:
      exists: true
      issuerName: "ca-issuer"
      clusterIssuer: true
      existingKeystoreSecretName: "nifi-tls-keystore-secret"
      existingKeystoreSecretKey: "password"
      certDuration: 2160h

  metrics:
    enabled: false
