apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: postgresql-auth-secret
  data:
  - secretKey: postgres-password
    remoteRef:
      key: /databases/postgresql/postgresql-auth-secret/postgres-password
      version: v1
  - secretKey: password
    remoteRef:
      key: /databases/postgresql/postgresql-auth-secret/password
      version: v1
  - secretKey: replication-password
    remoteRef:
      key: /databases/postgresql/postgresql-auth-secret/replication-password
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-initdb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: postgresql-initdb-secret
  data:
  - secretKey: init.sql
    remoteRef:
      key: /databases/postgresql/postgresql-initdb-secret/init.sql
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-initdb-credential
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: postgresql-initdb-credential
  data:
  - secretKey: POSTGRESQL_INITSCRIPTS_USERNAME
    remoteRef:
      key: /databases/postgresql/postgresql-initdb-credential/POSTGRESQL_INITSCRIPTS_USERNAME
      version: v1
  - secretKey: POSTGRESQL_INITSCRIPTS_PASSWORD
    remoteRef:
      key: /databases/postgresql/postgresql-initdb-credential/POSTGRESQL_INITSCRIPTS_PASSWORD
      version: v1
---
{{- if .Values.pgbouncer.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgbouncer-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: pgbouncer-auth-secret
  data:
  - secretKey: authUsername
    remoteRef:
      key: /databases/postgresql/pgbouncer-auth-secret/authUsername
      version: v1
  - secretKey: authPassword
    remoteRef:
      key: /databases/postgresql/pgbouncer-auth-secret/authPassword
      version: v1
{{- end }}
