apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: postgresql-auth-secret
  data:
  - secretKey: postgres-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 0110d767-be52-40bb-ab49-b2bc010a36ab
      version: v1
  - secretKey: password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 328bf325-c792-4430-afb4-b2bc010a5d3a
      version: v1
  - secretKey: replication-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: ba3810a8-ec10-422e-bd10-b2bc010a6c0f
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-initdb-secret
spec:
  refreshInterval: 1h
  target:
    name: postgresql-initdb-secret
  data:
  - secretKey: init.sql
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 554dbe7e-27cb-4e62-b7d8-b2bc010aae81
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-initdb-credential
spec:
  refreshInterval: 1h
  target:
    name: postgresql-initdb-credential
  data:
  - secretKey: POSTGRESQL_INITSCRIPTS_USERNAME
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 0edb8881-8f6c-4511-9151-b2bc010ad327
      version: v1
  - secretKey: POSTGRESQL_INITSCRIPTS_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 5ea4424d-870b-4b08-943e-b2bc010b0eee
      version: v1
---
{{- if .Values.pgbouncer.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgbouncer-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: pgbouncer-auth-secret
  data:
  - secretKey: authUsername
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: b0fd9b0e-78f3-4750-96a8-b2bc010b3153
      version: v1
  - secretKey: authPassword
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: c2a6f0ff-94cb-4710-be5d-b2bc010b4282
      version: v1
{{- end }}
