apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: keycloak-auth-secret
  data:
  - secretKey: keycloak-password
    remoteRef:
      key: /security/keycloak/keycloak-auth-secret/keycloak-password
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-pg-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: keycloak-pg-secret
  data:
  - secretKey: keycloak-pg-password
    remoteRef:
      key: /security/keycloak/keycloak-pg-secret/keycloak-pg-password
      version: v1
