apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudflare-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .accountId }}",
            "TunnelID": "{{ .tunnelId }}",
            "TunnelSecret": "{{ .tunnelSecret }}"
          }
  data:
    - secretKey: accountId
      remoteRef:
        key: 43772466-b145-4f94-b795-b3e5011596cc
    - secretKey: tunnelId
      remoteRef:
        key: 364c99ea-0af4-4557-88bd-b3e50116a68e
    - secretKey: tunnelSecret
      remoteRef:
        key: c692d24b-f0b1-4f6b-9a62-b3e50116833b
