releases:
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: 0.12.1
    values:
      - ./external-secrets.yaml.gotmpl
      - fullnameOverride: external-secrets
  
  - name: bitwarden-secret-store
    namespace: external-secrets
    chart: ./secret-store
    needs:
      - external-secrets/external-secrets
