apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6akNDQWJhZ0F3SUJBZ0lKQU1XYXFBMk9KVTZqTUEwR0NTcUdTSWIzRFFFQkN3VUFNQlF4RWpBUUJnTlYKQkFNTUNXTmhMV2x6YzNWbGNqQWVGdzB5TmpBeE16RXhOekEwTWpCYUZ3MHlOekF4TXpFeE56QTBNakJhTUJReApFakFRQmdOVkJBTU1DV05oTFdsemMzVmxjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBTW1QR2NFb3BnQjd5L3h6dFhXWDh1UzBCV3ZyQlg4Tm9qaVlxbEdWNXhBSTZXMnVobzcydmZka3hyOVAKcndlWXhOV3R0VjFGS2RGdFg0amN2VlYwbGI1S3IwNjQxNzF6amxQU09zK2k1NVVtemxHTlVXcTdtZ0t5VkREVQp0cGxZSW1KY0lhWjBhR2xlci9PTmNXbUJmRHZBSy9JUFM0WmhFbCthOVEzNXlmZzdpeVdmUWlSNFVoZ3pQcGRSCjdxYlV5SjgySzEzMEJnZXYySkJxR25IdUFHbDYycStTZW9MQzd6SEpxcVpoclpyUXhBMGR2NitZUDVxZElXSjAKQ2RvbXdtMG8wcGR6SXNyWXlwTXk3MUJmdFBGdkdaeXB3WVpOY1lrQnVjb2dYUndwMWpIdkJaRHk5Qy9tcmtpOApsNUNpalljdzVQSDBKYzFhYUxiVElXOUFQNlVDQXdFQUFhTWpNQ0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPCkJnTlZIUThCQWY4RUJBTUNBUVl3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUM3QnoycVJtSitTalF3QUhjSG8KbEFWK1JOalZXUHc2MTR3d0gwdTBnVkRYWVA3YU1LUldzcktGTGNtQzM5eXdva1lONmREVWZCQSsvWUZ0ajdMSApWNGNtTEczUFR0Y0tncmFsRWprSWxzTzNQOGJWUmRRRGpxeTBVdmVqTGtDaW5xT0VZUVhaSXY4MXRKbkxkdUpjCkZwaEp0N2xTNW1ZUTlhZFV0emdweTM5cjYxckQ5NDJvWkRCNyttZUxnd1RnV1ZQRWJvK1RENjRwUHV3OG1uMVIKY3ZYZGo5b1RjZ0prSFRwRFY1UXlVcDhRc2p6a3NBSjEzQ3F4SkQxbmpIQ28weXJieUpGSWdLakNCeFpja0tCbwprUjdCWlFwUExma3lnQVlRMmNtTEkrbmVON1dpYTFPTElWejBreHFDZVZoWkNITUR0b09xc1VLRFgrZ2FodFBiClFtcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoK
      organizationID: a0a949c0-6a91-45ec-8cd6-b258003b204d
      projectID: 4e2b83a1-7ca5-45eb-aafc-b258009364ab
---
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: fake
# spec:
#   provider:
#     fake:
#       data:
#         # Airflow
#         - key: "/computation/airflow/airflow-auth-secret/airflow-fernet-key"
#           value: "ujjkDJlmIKZalwVrotnOnqdVuIlcjVwDcdxrixy8yrc="
#           version: "v1"
#         - key: "/computation/airflow/airflow-auth-secret/airflow-password"
#           value: "iTTwF3v3NaazAda7CJDMX0Ln96976xWDks5EC60tNV4="
#           version: "v1"
#         - key: "/computation/airflow/airflow-auth-secret/airflow-secret-key"
#           value: "Kg/nCWZHF1pA/34YbQGievjj8xkbG/XSMIZ5WWa8uQE="
#           version: "v1"
#         - key: "/computation/airflow/airflow-pg-secret/airflow-pg-password"
#           value: "5rqnnupKlZ+eoa/thgCbz6me7IrBVitm0dE7wwzm94U="
#           version: "v1"
#         - key: "/computation/airflow/airflow-redis-secret/redis-password"
#           value: "G5FoLUdi/A1v3C2ZYK972oou3UByNkkSw5VngfCyUog="
#           version: "v1"

#         # Jupiterhub
#         - key: "/computation/jupyterhub/jupyterhub-pg-secret/jupyterhub-pg-password"
#           value: "ssYZ6axWb72EiSGbvtw2g+5vAZlYWglTX5Hfd9gNVIM="
#           version: "v1"

#         # Nifi
#         - key: "/computation/nifi/nifi-tls-keystore-secret/password"
#           value: "GpeCmJzS+x4ki74gTXJ+Cd/gSKTcI1JVMUzt5j2ZaBc="
#           version: "v1"

#         # Elasticsearch
#         - key: "/databases/elasticsearch/kibana-auth-secret/kibana-password"
#           value: "qyEDqgXFvpNhLMhbZkBPx1MvDpm9RkfdizsNvRgE6Eo="
#           version: "v1"

#         # Mysql
#         - key: "/databases/mysql/mysql-auth-secret/mysql-root-password"
#           value: "S+6yWIbgyf5F32eooH3FNWjvEcrjM0SvxHSVYDVbJFQ="
#           version: "v1"
#         - key: "/databases/mysql/mysql-auth-secret/mysql-replication-password"
#           value: "4fnqwP+CTLKvD/xWWsJyPfsksAKMSeFZEVHQXwr7eho="
#           version: "v1"
#         - key: "/databases/mysql/mysql-auth-secret/mysql-password"
#           value: "2c71fFznrEcEnENSJgItG70WkOMbh2NyOrVB8ML1P3E="
#           version: "v1"

#         # Postgresql
#         - key: "/databases/postgresql/postgresql-auth-secret/postgres-password"
#           value: "eAcUdxJJyLvGbIUUt3dohl/KOCfzxF4xucbq+cUUCrg="
#           MG1WvY6/Ho7+GFurLBwvMjoy4Izj3LlLsHw1JWTbDB/Gt7YxsYqHCzVmrJwDNiD1
#           version: "v1"
#         - key: "/databases/postgresql/postgresql-auth-secret/password"
#           value: "KHkbNOLRWkaSLOqF3Qa/RcXUmiDzhWbaMHUILp3QpwU="
#           version: "v1"
#         - key: "/databases/postgresql/postgresql-auth-secret/replication-password"
#           value: "x/x/3xXFiVhBb7SgkeQKO7cw4mE9zeaVBgHH1la86Rs="
#           version: "v1"
#         - key: "/databases/postgresql/postgresql-initdb-secret/init.sql"
#           value: |
#             CREATE USER airflow WITH ENCRYPTED PASSWORD '5rqnnupKlZ+eoa/thgCbz6me7IrBVitm0dE7wwzm94U=';
#             CREATE DATABASE airflow OWNER airflow;
#             CREATE USER jupyterhub WITH ENCRYPTED PASSWORD 'ssYZ6axWb72EiSGbvtw2g+5vAZlYWglTX5Hfd9gNVIM=';
#             CREATE DATABASE jupyterhub OWNER jupyterhub;
#             CREATE USER keycloak WITH ENCRYPTED PASSWORD 'V9QSDwgvmCUrRU0Bjq41EqUyNj/gUVk/RerEIQSq+Nw=';
#             CREATE DATABASE keycloak OWNER keycloak;
#             CREATE USER codeserver WITH ENCRYPTED PASSWORD 'PrMY+AApVPVJH9DQz+/DN/gSOmscmi2edVK3KxBw/bQ=';
#             CREATE DATABASE codeserver OWNER codeserver;
#           version: "v1"
#         - key: "/databases/postgresql/postgresql-initdb-credential/POSTGRESQL_INITSCRIPTS_USERNAME"
#           value: "postgres"
#           version: "v1"
#         - key: "/databases/postgresql/postgresql-initdb-credential/POSTGRESQL_INITSCRIPTS_PASSWORD"
#           value: "eAcUdxJJyLvGbIUUt3dohl/KOCfzxF4xucbq+cUUCrg="
#           version: "v1"
#         - key: "/databases/postgresql/pgbouncer-auth-secret/authUsername"
#           value: "postgres"
#           version: "v1"
#         - key: "/databases/postgresql/pgbouncer-auth-secret/authPassword"
#           value: "eAcUdxJJyLvGbIUUt3dohl/KOCfzxF4xucbq+cUUCrg="
#           version: "v1"

#         # Redis
#         - key: "/databases/redis/redis-password-secret/redis-password"
#           value: "0sH9Rolra4vdMyE3T4KXfRUdOdKQ5yTzMkSpiABaDbM="
#           version: "v1"

#         # Grafana
#         - key: "/monitoring/grafana/grafana-auth-secret/grafana-password"
#           value: "qjZf1Ylu+7cOmF5HqeuF19mFdZkM6es7xcQ9J08snR0="
#           version: "v1"

#         # Code-server
#         - key: "/others/code-server/code-server-secret/code-server-password"
#           value: "MEQucR/SM/uHRbhFdy6u78x7a9OTvuVyWwp7NZZrTjE="
#           version: "v1"

#         # Keycloak
#         - key: "/security/keycloak/keycloak-auth-secret/keycloak-password"
#           value: "+ubLQtoN3FtSXFwkMF74Mpf/r+qyP9Bd0g40bfsdo/o="
#           version: "v1"
#         - key: "/security/keycloak/keycloak-pg-secret/keycloak-pg-password"
#           value: "V9QSDwgvmCUrRU0Bjq41EqUyNj/gUVk/RerEIQSq+Nw="
#           version: "v1"

#         # Minio
#         - key: "/storage/minio/minio-auth-secret/root-user"
#           value: "minio"
#           version: "v1"
#         - key: "/storage/minio/minio-auth-secret/root-password"
#           value: "Yarp/mKorl857anyhe5kswyEWB/H/nApYgeLbe0jf6E="
#           version: "v1"

#         # Clickhouse
#         - key: "/warehouse/keycloak/clickhouse-auth-secret/clickhouse-password"
#           value: "8CDscshKlh+PxMP43/IIfE2zsrjbuIJ8jNOcvUYVsEo="
#           version: "v1"
