version: '3'

silent: true

dotenv:
  - .env

includes:
  cluster:
    taskfile: ./clusters/Taskfile.yml

tasks:

  lab-on:
    cmds:
      - task: cluster:up
      - task: core-services

  lab-off:
    cmds:
      - task: cluster:down

  lab-status:
    cmds:
      - task: cluster:status

  lab-delete:
    cmds:
      - task: cluster:delete

  core-services:
    dir: core
    cmds:
      - helmfile repos
      - helmfile apply
      - kubectl apply -k ./
