version: '3'

silent: true

dotenv:
  - .env
  - .env.default

includes:
  cluster:
    taskfile: ./clusters/Taskfile.yml

tasks:

  lab-on:
    cmds:
      - task: cluster:up

  lab-off:
    cmds:
      - task: cluster:down

  lab-status:
    cmds:
      - task: cluster:status

  lab-delete:
    cmds:
      - task: cluster:delete

  core:
    dir: core
    cmds:
      - helmfile apply

