{{- $hiveserver2 := mergeOverwrite (deepCopy .Values.commons) .Values.hiveserver2 -}}
{{- if $hiveserver2.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hive.fullname" . }}-hiveserver2
  labels:
    {{- include "hive.hiveserver2.labels" . | nindent 4 }}
    {{- with $hiveserver2.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $hiveserver2.annotations | nindent 4 }}
spec:
  replicas: {{ $hiveserver2.replicas }}
  serviceName: {{ include "hive.fullname" . }}-hiveserver2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "hive.hiveserver2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hive.hiveserver2.selectorLabels" . | nindent 8 }}
        {{- with $hiveserver2.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "hive.checksum" . | nindent 8 }}
        {{- with $hiveserver2.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
        - name: hiveserver2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["/usr/local/scripts/hiveserver2-entrypoint.sh"]
          env:
            {{- toYaml $hiveserver2.env | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "hive.fullname" . }}-hive-env
          ports:
            - name: hs2
              protocol: TCP
              containerPort: 10000
            - name: hs2-webui
              protocol: TCP
              containerPort: 10002
          volumeMounts:
            {{- include "hive.volumeMounts" . | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: hs2
            periodSeconds: 30
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: hs2
            periodSeconds: 30
          resources:
            {{- toYaml $hiveserver2.resources | nindent 12 }}
          securityContext:
            {{- toYaml $hiveserver2.securityContext | nindent 12 }}
      serviceAccountName: {{ include "hive.serviceAccountName" . }}
      priorityClassName:  {{ $hiveserver2.priorityClassName }}
      runtimeClassName:   {{ $hiveserver2.runtimeClassName }}
      schedulerName:      {{ $hiveserver2.schedulerName }}
      securityContext:
        {{- toYaml $hiveserver2.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "hive.volumes" . | nindent 8 }}
    {{- with $hiveserver2.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $hiveserver2.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $hiveserver2.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
