fluent-operator:
  containerRuntime: docker
  Kubernetes: true

  operator:
    initcontainer:
      repository: "docker"
      tag: "20.10"

      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi
    container:
      repository: "kubesphere/fluent-operator"
      tag: "v3.1.0"

    resources: {}

  fluentbit:
    # FluentBit is built on 4Kb page size system and is not compatible with my raspberry which is based on a 16Kb one.
    # Changing page size might be an option but is not recommended as it could cause performance issues on either of them - or both
    # Using Fluentd as an alternative is a great idea due to its independence from the underlying hardware
    enable: false
    crdsEnable: false

  fluentd:
    enable: true
    crdsEnable: true
    name: fluentd
    mode: "collector"
    port: 24224
    image:
      repository: "ghcr.io/fluent/fluent-operator/fluentd"
      tag: "v1.17.1"
    replicas: 1
    forward:
      port: 24224
    watchedNamespaces:
      - kube-system
      - argocd
    resources: {}
    output: {}
