redis:
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.4.0-debian-12-r4

  architecture: replication

  auth:
    enabled: true
    existingSecret: "redis-password-secret"
    existingSecretPasswordKey: "redis-password"

  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""

  master:
    count: 1

    disableCommands:
      - FLUSHDB
      - FLUSHALL

    containerPorts:
      redis: 6379

    ## Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
    resourcesPreset: "nano"
    resources: {}

    persistence:
      enabled: true
      path: /data
      accessModes:
        - ReadWriteOnce
      size: 8Gi

    service:
      type: ClusterIP
      ports:
        redis: 6379

  replica:
    kind: StatefulSet
    replicaCount: 3

    disableCommands:
      - FLUSHDB
      - FLUSHALL

    containerPorts:
      redis: 6379

    ## Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
    resourcesPreset: "nano"
    resources: {}

    persistence:
      enabled: true
      path: /data
      accessModes:
        - ReadWriteOnce
      size: 8Gi

    service:
      type: ClusterIP
      ports:
        redis: 6379

  sentinel:
    enabled: false


  tls:
    enabled: false

  kubectl:
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: 1.31.1-debian-12-r1

  sysctl:
    enabled: false
