apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: mysql-auth-secret
  data:
  - secretKey: mysql-root-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 949d7b3e-65a5-4a4d-b794-b2bc010a0311
      version: v1
  - secretKey: mysql-replication-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 01fe1461-a791-4a43-97ae-b2bc010a1583
      version: v1
  - secretKey: mysql-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: af957cad-1ee0-4d7e-bc7d-b2bc010a249d
      version: v1
