apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: mysql-auth-secret
  data:
  - secretKey: mysql-root-password
    remoteRef:
      key: /databases/mysql/mysql-auth-secret/mysql-root-password
      version: v1
  - secretKey: mysql-replication-password
    remoteRef:
      key: /databases/mysql/mysql-auth-secret/mysql-replication-password
      version: v1
  - secretKey: mysql-password
    remoteRef:
      key: /databases/mysql/mysql-auth-secret/mysql-password
      version: v1
