galaxy_info:
  author: Do Ngoc Son
  description: This role is to build up my own homelab

  license: Apache-2.0

  min_ansible_version: 2.1

  galaxy_tags:
    - fabricator
    - homelab
    - common
