apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unitycatalog-pg-secret
spec:
  refreshInterval: 1h
  target:
    name: unitycatalog-pg-secret
  data:
  - secretKey: unitycatalog-pg-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: b3f17daf-5903-4810-acb8-b36401082886
      version: v1
