localstack:
  replicaCount: 1

  image:
    repository: localstack/localstack
    tag: "3.8.1"

  serviceAccount:
    create: true

  role:
    create: true

  startServices: ""

  service:
    type: ClusterIP
    edgeService:
      name: edge
      targetPort: 4566
      nodePort: 31566
    externalServicePorts:
      start: 4510
      end: 4560

  ingress:
    # Use cloudflare tunnel instead
    enabled: false

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  resources: {}
