apiVersion: v2
appVersion: 1.0.0
description: A helm chart for kube-prometheus-stack deployed through argocd
maintainers:
- name: Do Ngoc Son
  email: dongocson.work@gmail.com
name: kube-prometheus-stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 87.2.0
    repository: oci://ghcr.io/prometheus-community/charts
