apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kibana-auth-secret
  namespace: elasticsearch
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    kibana-password: AgAgFefJ5LB560Df3c2VhLQ8sKQP1OAQVq13DKkEK069LoUCt52Q1H9k+LdPaK+ED+pR2yYm0JXE6Z7qfhyroQpuFZhCOxFOxZEtIzlXR8GADT0PPobz6yzphAHfE8iscTILF7qN3rnlE0mzM/Fh1uHYRmk++GmKJu1GdoYm4MoCtpqnL7zA1QulOTcaeuKsqWh/RpHHZOrbZYH/+YnEAuCj6jm27M75DSBUCy+8mdLxISpw/tx+2Z9UrVK+FN1mMVnoiSI8fMhtxPqXouUWmVOIERVUa3qPSy7Qi6fgR8DKUFSOAhRproFjO2L3+0dh3e83ofBrye+YuG0r2REol7ZtguTtFB8J+giW0by+mWc1DlwYaus+vEzXIK3Dj3cy0nIlrUctV+aoP/F7JiggD+HZHjnc+wQeCsegvBfaysAOih/FMS/zQKP2G9/Ap5qUCuaCJ2PPTL9kFstvVSiamnZFvbo4ZEVbZj0x8WG73DV1/uVGwVbTyv93SiSxXFH9dZT7dopbnVA+kTlTN5V2Dx10H1BiiqcB4KooU9e1o9DDLt9c+oQjPM/qY+2IereiFUqyxYpi+3zQslxB/RACWPx9l+xup4/QHacKPi0CVaQInhjYcv5z4LSkx1rx9YduIOEU1kCHd2Ag7WRaZPU/UjRM1BYTcnWfdWRB18qxWr/vIttebgI4XLR/kGj6lNZ+HjAxRX6x4FPnWl7giQ==
  template:
    type: Opaque
