apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kibana-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.fabricator.secretStore }}
    kind: ClusterSecretStore
  target:
    name: kibana-auth-secret
  data:
  - secretKey: kibana-password
    remoteRef:
      key: /databases/elasticsearch/kibana-auth-secret/kibana-password
      version: v1
