apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kibana-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: kibana-auth-secret
  data:
  - secretKey: kibana-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 8c419797-b7b3-47fc-84c4-b2bc0109f194
      version: v1
