apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: minio-auth-secret
  data:
  - secretKey: root-user
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 2a58b3ca-a53d-4922-b8fe-b2bc010bde57
      version: v1
  - secretKey: root-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: b7aff8fa-2c6a-482c-96cb-b2bc010bfbfd
      version: v1
