apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: minio-auth-secret
  data:
  - secretKey: root-user
    remoteRef:
      key: /storage/minio/minio-auth-secret/root-user
      version: v1
  - secretKey: root-password
    remoteRef:
      key: /storage/minio/minio-auth-secret/root-password
      version: v1
