kube-prometheus:
  operator:
    enabled: true

    image:
      registry: docker.io
      repository: bitnami/prometheus-operator
      tag: 0.76.1-debian-12-r2

    serviceAccount:
      create: true

    service:
      type: ClusterIP
      ports:
        http: 8080

    ## Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
    resourcesPreset: "none"
    resources: {}

    kubeletService:
      enabled: true
      namespace: kube-system
