releases:
  - name: argo-cd
    namespace: argo
    chart: bitnami/argo-cd
    version: 6.6.10
    values:
      - ./argocd.yaml.gotmpl
      - fullnameOverride: argocd
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["apply", "-f", "../bootstrap.yaml"]
  - name: argo-events
    namespace: argo
    chart: argo/argo-events
    version: 2.4.14
    values:
      - ./argo-events.yaml.gotmpl
      - fullnameOverride: argo-events
  - name: argo-workflows
    namespace: argo
    chart: argo/argo-workflows
    version: 0.45.11
    values:
      - ./argo-workflows.yaml.gotmpl
      - fullnameOverride: argo-workflows
