releases:
  - name: argo-cd
    namespace: argo
    chart: bitnami/argo-cd
    version: 6.6.10
    values:
      - ./argo-cd.yaml.gotmpl
      - fullnameOverride: argocd
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["apply", "-f", "../bootstrap.yaml"]
