releases:
  - name: argo-cd
    namespace: argo
    chart: argo-cd/argo-cd
    version: 9.0.0
    values:
      - ./argo-cd.yaml.gotmpl
      - fullnameOverride: argo-cd
    # hooks:
    #   - events: ["postsync"]
    #     command: "kubectl"
    #     args: ["apply", "-f", "../bootstrap.yaml"]
