apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-git-repo-secret
  namespace: argo
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore  
  target:
    name: argocd-git-repo-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "git"
        url: "https://github.com/sondn98/fabricator.git"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "34fe44ab-ccff-4beb-b64d-b3e6010ac4e2"
    - secretKey: password
      remoteRef:
        key: "f08af11e-4bed-4c00-bab5-b3e6010bf833"
