apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fabricator-creds
  namespace: argocd
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: type
      remoteRef:
        key: "fe34b15e-0967-40c5-882f-b25b004fdf09"
    - secretKey: url
      remoteRef:
        key: "3e508ef2-ef99-439c-b559-b25b00510cfa"
    - secretKey: username
      remoteRef:
        key: "2f866246-1e26-4e2d-8668-b25b005156cf"
    - secretKey: password
      remoteRef:
        key: "f23b930a-7020-4e4c-a62a-b25b005194b4"
