apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    redis-password: AgB0783wHCpoYAZSITpyGEXsFlunZUsT0Dmw9x2aBMmR1ubqr63mdPKY48SRrQEc3ygUBv3NF9PGeZOSWkkw9Im0YyMs2MXIBC01rVhuBPGqm8zCTy5cqusgxW1Ss+AUaGf3TJbKoQaAP8qEvpDcfAibcOTiJg5CAXi51U/Axm/XmDDKU5Rtk0NRgyR0amI3dXXSIjyPmUiEZM4h1AvVsYLueZphm8e5pYN7DNrbEpxWh5SUgWQLgVOlJ8f/hW3jBNVZ/DT3eKRRQ74j8EvwkmYJuUlpzOsOckuZZmeVDjc1FWgQKyIXSsLnrPuQaFYP8IEM4fYtypYvdtX4IYhlBYhdtBWiUz7lsB2zjH+uaZHfocvF7LU8mP6PC7H0O+iujxdq/T3Tv8WV/+fPThZGRu1ZZtPmFjaIRCAT33/tyAG0SCmG2rfS/3l9aY7kpQwkYI/hACOPJtcvoXeByenZmoAD084E6m7nixDreN0nDOx+MaCWK02kaIZBotraiWqiuBsbqtNsh8k9XeytGvHB7LBy1l24Ua2x5216kHQ0VO8AraL2FcemZuheZ84TgBMCAh1ifEjGn8ZKwfbrLANz0rROcj65fT/LTHgp0ZEKDdDFv5YBR/3l8QVSXpPg6hNGh1spQcjUuddUTwwFOBzPlKLdARIeTM60qh1XQnjdjD7x848IqyXBKqX7hmYEJ8hGnkOisnJ8NxMru0zRTg==
  template:
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    admin-password: AgAjOQyGEydQ7oDh4V+hMrNSojVVWR2nian+zHPAThK3LIT0jaEkeaqq5XTHMgxhnqzX3LQPsHv1CJRDT6Z3A9MqYMwnV+39keCzKdx2KSEeeN16k/dPgbifEeGH28oXs1xrVzUeEEOlmvi27c/nqrmWkqKEWN3JEB7LAHjQYMeeh+Ce3myV0FxOPN9Q/NZHOI8t3WHDBJGbyqXybfiJ/pbDdlAX9BsJWQxUVgTroytde8/5irkv+t6QqXEAIacNBTP0BIMpRzUYgOepKS04F1Q+8XDGb4h4llKIhlcuwECtbKjAn7l5je17HpenpC7WDEze+dLtAjoyytp/dd4yelYi9Blwp6W/Z/NL19WlR6Bmn4JwR/e0pFCZz1tFyqAe8OOXkLT8BzyOo8NQU3eRHJtPcuc0ombrLAEaPC9RxoMkttMJijvTWJhjXNQDo5cNQWj0hlvKuJyGgWrkZX0x6RVHBh14GBGcetx9ryL21ytdpORYdOIOUR4yJZbuUGqMbdS5mrJ0I7Nx9v475KxZ6azkEQKjOCjUYvSiDJq17gVplx22pNqakOtgHTomdUXNAYN2Z0kDkX87mOf0Dp2EKXDEPHYhM0d12Z/BrtgOLuz6fVtRKiufZVFW0p3FaU/bX8tQlXJiNM5SQqBdWxVdtPffYcGp0A5qd5iJ9BMp8fYTnPY19/oYrTCs+eoMTXhagIzBTec86wwuzM3H+g==
  template:
    type: Opaque
