apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    redis-password: AgA58nlJzQ6Pu3w2e+TryaxaU6Hzj2cJi93FuRUN5Ex2w1SFkHAmMzVhoqaPtJz8+J8O4Sj9eH5QzQ4PdtS+sZqy5gR0oIET9lXfPNfjoIGMr1bQirgxJ7+cPib5mApMkXhxwdJwbsjYhNtjyzLfHhPNgJKcyhKbq7Nryc/XVJ42GFBPh0uDmWE85WKWYYNmc6alJr++mv9eyruldK+kt0azBCiLtUwdymySDC/9CYGHNe9iT/xezmSR4eulxPqe0bzPxhsKlk1TlzsDrC5CbD6AfzhiHA82qyfnCgitslZGNmHsNXSjnXMPnp67SrL9OAbytrcvf7xp2efrq9vl/ehZf5XE+e75zlgOwE2ybCeTqEdXibaSoycvwe+8oEtclUYV8UU/F1xJVy5Sjoqlhq9Ocac49Y5Lt7uI0hMkZEzPMtyUgBxJIkrECAfGgq421o1yw7diE+w56Ih/0Qdc14MKNPMD7UFgQ0XovTi+EPqaDzISLh7uQ4KNnJH4/70hHlVUxAbsSjELTMeBh3z8ZS3psOhnYLIRFj8+1EWnsEt346AuNnFjoAHvKPsFpJrsC8ssVeSnXc3XO7xTIQIb99XsDu9ohfu28KB5MW6++sunG2kuHH4/9rxKXthrhp/hhy6wZL3saTFXVznWR2ozGkW+36dYla9ZzWnqip0d/QXVaoErKDw3tuSpjPnz1jp4o7yM1eDmpt3BwTCHBg==
  template:
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    admin-password: AgBlIWmWCByKYeHRBb0dzO26JJsYaqmZKcwCbSrRlccYm+8V1AXHOds8yRnxGEIO0LiXlijDN3GcfbAB8J0CZ3XcpNqXiALd8PL27DJ0Z3iYHyx9cPRVCUb9DzcRhczPHDzWsGvemZsZYig5bbZ6102Gg6eIy6iNuJPjevZPd4hdFnjthHVHaihGEsLmNyVEv2wahVRXlyTa9LZDQCJpo/kYv6FLCre1w9f8qgIiGhOTY8ZY8oL/UpuKnRwpirEbUJx8QNUEF/mCPhHY7dw0YD1A2wqXIA61Bo4UcWEZPVeNC2eWbmutFj7LOicm/rJ2AEAvKBRE0/wdCmariKOquM0NGbwGCAQswgig0ULRDOnI/L3MPvoYNUe2zMuWgS0i09rbfePKTCALYoB8w8jwUUmfxsWYqOVqv1ymiFbIWZyAdqgXEI2e0ll8hQbefvrNq/WR4EigPmhuXICFpBajwbTiTR16WMHt42HHBOWYqplnJEVllJOWAbL532T/aFDUsdNzEEKjGIFWFC8CIVZB0JCY4krmYgAL/CTAC0tgue6JjOPL2f4yyOvh7WiOPGi4RL2JTN6GPnR7LNpT+LOJi2+o48etIgFE5ERnzcGY5UTmxRu2NZZTvBiSfTRUrAVg3pPWa4OkJw9CObEVDSQKDcEp/uM20hd0y4X1N1FbRKpuY2zYmoLz4USQUyIrKlSIoWRBQT6yv/k2juTJOg==
  template:
    type: Opaque
