---
- name: Setup essential tools
  ansible.builtin.include_tasks:
    file: common.yml

- name: Setup K3S server
  ansible.builtin.include_tasks:
    file: master.yml
  when: "'master' in group_names"

- name: Setup K3S agent
  vars:
    master_token: "{{ hostvars[groups['master'][0]]['master_token'] }}"
    master_ip: "{{ hostvars[groups['master'][0]]['master_ip'] }}"
  ansible.builtin.include_tasks:
    file: worker.yml
  when: "'worker' in group_names"

