---
## Install K3S server
- name: Get installation file
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: '0755'

- name: Install K3S server
  environment:
    INSTALL_K3S_EXEC: |
      server
      --flannel-backend none
      --disable=traefik
      --disable-network-policy
      --node-ip={{ ansible_default_ipv4.address }}
      --bind-address=0.0.0.0
  ansible.builtin.command:
    cmd: |
      /tmp/install_k3s.sh

- name: Change k3s kube-config file permissions
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0604'

- name: Get server token
  slurp:
    src: /var/lib/rancher/k3s/server/token
  register: token

- name: Share server info for agents to join
  set_fact:
    master_token: "{{ token['content'] | b64decode | trim }}"
    master_ip: "{{ ansible_facts[homelab_master_network_interface]['ipv4']['address'] }}"

## Install essential tools
- name: Install Helm
  ansible.builtin.include_tasks:
    file: downloader.yml
  vars:
    bin_name: helm
    url: https://get.helm.sh/helm-{{ homelab_tools_helm_version }}-{{ homelab_os }}-{{ homelab_arch }}.tar.gz
    dest: /tmp/helm.tar.gz
    need_decompress: true
    tmp_bin_relpath: "{{ homelab_os }}-{{ homelab_arch }}/helm"

- name: Install Helm diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

- name: Install Helmfile
  ansible.builtin.include_tasks:
    file: downloader.yml
  vars:
    bin_name: helmfile
    url: https://github.com/roboll/helmfile/releases/download/{{ homelab_tools_helmfile_version }}/helmfile_{{ homelab_os }}_{{ homelab_arch }}
    dest: /tmp/helmfile
    need_decompress: false
    tmp_bin_relpath: "helmfile"

## Install Cilium
- name: Copy core folder to remote
  ansible.builtin.copy:
    src: "../core"
    dest: "/tmp"
- name: Add Bitnami repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
- name: Install Cilium
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  ansible.builtin.command:
    chdir: "/tmp/core/cilium"
    cmd: helmfile apply
