---
## Install K3S agent
- name: Get installation file
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: '0755'

- name: Install K3S agent
  environment:
    INSTALL_K3S_EXEC: |
      agent
      --node-ip={{ ansible_default_ipv4.address }}
      --bind-address=0.0.0.0
      --server=https://{{ master_ip }}:6443
      --token={{ master_token }}
  ansible.builtin.command:
    cmd: |
      /tmp/install_k3s.sh
