releases:
  - name: metallb
    namespace: kube-system
    chart: bitnami/metallb
    version: 6.3.10
    values:
      - ./metallb.yaml.gotmpl
      - fullnameOverride: metallb
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["apply", "-f", "address-pool.yaml"]
