---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trino.demo.com
  namespace: trino
spec:
  duration:    2160h # 90d
  renewBefore: 360h  # 15d
  subject:
    organizations:
      - demo
  isCA: false
  usages:
  - server auth
  - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: trino.demo.com
  dnsNames:
  - trino.demo.com
  issuerRef:
    name:  ca-issuer
    kind:  ClusterIssuer
    group: cert-manager.io
  secretName: trino.demo.com-tls
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key:  keystore.key
        name: trino-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: trino-secret
  namespace: trino
type: Opaque
stringData:
  keystore.key: jTATy27H2jQquoGHTxar3gGXgdg354GSA
