apiVersion: v1
kind: Secret
metadata:
  name: homelab.local-ca
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGDTCCA/WgAwIBAgIUapOFcQ2A3kUfqGjHByheM4gTn0EwDQYJKoZIhvcNAQEL
    BQAwgZUxCzAJBgNVBAYTAlZOMQ4wDAYDVQQIDAVIYW5vaTEOMAwGA1UEBwwFSGFu
    b2kxEzARBgNVBAoMCkZhYnJpY2F0b3IxEDAOBgNVBAsMB2hvbWVsYWIxFjAUBgNV
    BAMMDWhvbWVsYWIubG9jYWwxJzAlBgkqhkiG9w0BCQEWGGRvbmdvY3Nvbi53b3Jr
    QGdtYWlsLmNvbTAeFw0yNDEwMTMwNzMyNTBaFw0yNzA4MDMwNzMyNTBaMIGVMQsw
    CQYDVQQGEwJWTjEOMAwGA1UECAwFSGFub2kxDjAMBgNVBAcMBUhhbm9pMRMwEQYD
    VQQKDApGYWJyaWNhdG9yMRAwDgYDVQQLDAdob21lbGFiMRYwFAYDVQQDDA1ob21l
    bGFiLmxvY2FsMScwJQYJKoZIhvcNAQkBFhhkb25nb2Nzb24ud29ya0BnbWFpbC5j
    b20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCkf2RPli+u29uP06iA
    4kh3+/b5VyuX2bU6/7a0XgsDobhrJQl3tHffjemdF7qhJg40s59w+q+NqBp8slzq
    lwNRuP+s9iXB+lZt0e2G62pweiQ4Ui87InEhbxoi3nCn5y9A3svje/fj7auxKAo8
    Ee22T7i0/A0+QROl+2SODM3ibMNsRUuRuYS/mS2T/MQgFmWuiA34TiMg0Ie1qjmA
    qmWYg4xdd+CSvXQWc4YpSfr5apXYP1mncfTnG++7h8rrmNHShHA2eaz3Mzz2z51C
    8LdtpeOY+BTN65eu0CfK3k6O+ZSuzMraRQ1QDdVOTcE8dI7bvo/ucJCROvHZM9Xu
    RBdWFAQ5BTknyrAASQXofYvUM8oAeb9R2ZXKi4XRqMm3/RD9mBZOt/gRRzmlC9Il
    QCk/TtKAZ9kRhEKmehJjT6+3Yv0Oev253MczrzRVzYsvxqepirhyNx9aCnGNd3GM
    81PXFpb5C8rxeS1lC8Jy4TzgbavTK/K9OiGqnLEttxtrfDu5p0DpqWg7tU7QvNmU
    c0h1k8nakOkQbS1eOK/vCHVuVtq+dYX+iHvtgDSqJWrFsBa9vBJxOVOHOxD9rV0p
    4FUqhsk/CRXIKu55kdCD3Obeq7hbE0zFeoUZkLIwjitSTDQKDjc87IzKI7jXwI1d
    r1jRg9h0sYzOfxpbVFKXkB1ZfQIDAQABo1MwUTAdBgNVHQ4EFgQUxY8QMXiOU+l+
    qoV7UvxgXw09ADEwHwYDVR0jBBgwFoAUxY8QMXiOU+l+qoV7UvxgXw09ADEwDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEACJ/bD9aEaiVxpgP18XlP
    rpXnFT43IDw8UJXmjdbjWHSwHpJ4fd99YlMPdBz3jIYV96AGfLafLu8QlOw/c9UI
    eKwIln0UyTB/wDUGrKPtogccEnINqM0jGa2BBqEmInfBIDUM2MWrmTr4B+znA5Kk
    slmw/PXicUukZGzZ+jGwmm+yTXtb6YrU96MUeS8PF7Tpk0WHEflFFm0Jtg2iChnv
    I+ASgyBQ0RgU4E59VLCwAI9ubr/LpeKErwpnP82rKmONlnrv7BqM4erg7r+7oAAa
    cPf/In8bVh2tSxqanvmky2w0KFZbUmZvSVpVPeoqZeyPerNjP8vLZfNYTGTJvNxJ
    IKi4JFMlfhCtPOHwiXbn2Ws6/dZG6gKcQH68lx4vxB8E/S5iRMyO/Yvhw8HVzDtI
    oGOYhiybw12cn2g983wMmCm8drlBTnnyy0/p6Ia3ZiWTuceBXzZQC0Tt1G2wXXkp
    mqdyM3vYvh7BbKImnxWN1aHIMgysCaRAFx2l2WNMMI2byEp6T3EZOSvln0VElFjs
    gTBBvfhF7LwN847gRLI9iwyYY93wXdgTSbZoar60ICEgvJvBGEvPOoVmTlNAw3l2
    4ienZWFBNWbk7aUN50wYMwFswRO1cmz40QCLiuDdERICFKYwqpDkkvOaq3xWVsd7
    QtWFijc+dvmEvvY166ahL20=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCkf2RPli+u29uP
    06iA4kh3+/b5VyuX2bU6/7a0XgsDobhrJQl3tHffjemdF7qhJg40s59w+q+NqBp8
    slzqlwNRuP+s9iXB+lZt0e2G62pweiQ4Ui87InEhbxoi3nCn5y9A3svje/fj7aux
    KAo8Ee22T7i0/A0+QROl+2SODM3ibMNsRUuRuYS/mS2T/MQgFmWuiA34TiMg0Ie1
    qjmAqmWYg4xdd+CSvXQWc4YpSfr5apXYP1mncfTnG++7h8rrmNHShHA2eaz3Mzz2
    z51C8LdtpeOY+BTN65eu0CfK3k6O+ZSuzMraRQ1QDdVOTcE8dI7bvo/ucJCROvHZ
    M9XuRBdWFAQ5BTknyrAASQXofYvUM8oAeb9R2ZXKi4XRqMm3/RD9mBZOt/gRRzml
    C9IlQCk/TtKAZ9kRhEKmehJjT6+3Yv0Oev253MczrzRVzYsvxqepirhyNx9aCnGN
    d3GM81PXFpb5C8rxeS1lC8Jy4TzgbavTK/K9OiGqnLEttxtrfDu5p0DpqWg7tU7Q
    vNmUc0h1k8nakOkQbS1eOK/vCHVuVtq+dYX+iHvtgDSqJWrFsBa9vBJxOVOHOxD9
    rV0p4FUqhsk/CRXIKu55kdCD3Obeq7hbE0zFeoUZkLIwjitSTDQKDjc87IzKI7jX
    wI1dr1jRg9h0sYzOfxpbVFKXkB1ZfQIDAQABAoICAAI3ik9NR568bVDaqih0hEQD
    tBAntdlx0HC3Xgu/wbe+j/j3spE3sC7l33pjxbriw6m/qvwvkLqgw5yfHcP2nY+W
    JfH7jkY3PL91pxUcqp5R8xeEOgk6vVoVQH2sUEnfAoLGDermspBSlXAJiVvGZRUC
    LYvY4sfOQjjIMtJ8RzEQRLD6nRpdbPXVF2lpbG4/RwcLY97PFMeeL9oJrYU3pq9f
    xH5E/ZSUs5IS5AG98sE2R8c2kVuBnGqZ9IjrO1eiA1/qM4X0bVmWifGMmkK68knq
    xK681zDwRibPvN2N0fK41+FkNq6q5BNKYG/R+fL54iwBfTiaMUSXzgcenPk9VzAm
    +llmCqm5KsWDGo5dNo8PPyP9cDAL2yUJueEoZQDm3yq30O16NUG8qo2XnhgFjHEy
    t22LBLjNqh7i33l9B8h94e5BnGw8zbkSzgd8N14e3syK3YWzysb1n8sekXm2TVIn
    3kXJYjHD/1WFVBsl4gM0ICVwsRmEHi+ynjuop0q4ZhvYuNEBNbcxW9XVmQ/ZVuop
    pO1cp7xlOtuMOSjIDfQLTOko515jcbR+RLTyg7KoXuC3jJvRAwdHyFq9s6en6Gxs
    2ypGIM8JdMggy8w52OupQe3IAAvUCbOZL9fXi1NRMJPxMCWI1PXyg23G7ekxKOd+
    zZBA1SdxMOAYQ3bA8NexAoIBAQDnIGbjKxxPVA4q+aOKZ6XFKFJIOTNvMmOHLQiy
    Wyam9KSaVzJBcKMrPo/JsRQdvD3Hq4a2FaBqkmBDrU4EHf+j2TVCaDDlMhua8Wdi
    +dWu5VSNEE3R+b6bCUjJYZY/xyT+hQ/YY0qzVWjenuMjYptbSTlhFU55K52suNd4
    6qPTwvboa62BBb0eHxg2sXuHH8955aDNH47ZCT3hfo2Ltyle/zwHhMBH1Qcp1RIz
    5D7YjCdP/EuxIxR3HNJW6ykruh0LwI6wMvTnB6ScPSkCy0KUGeAou6EhSo0ZEB0R
    kOu0bMJfjeAwFJ6ux5cyy97s7Isz+s3qqD1ujVCzmTe2Jl5RAoIBAQC2M1hJmZkL
    e6GUEKBQ2qDUc6wkSOUWWiiFkPmTekrxFQDQDgHUuy6oLbraBe05xK7gv5KZjr4o
    a37OKm5YwChyI00Sax4YkCFGAvAVivNGqfA5atJaI5Ptjwk7CpfFcAOOati1CmzS
    bDt1fUX7G2LQDj0XTGFuOdqP6Jr3s5svXmMAuVhDtex9hw0alYbfVFdkkkWf0Zti
    XEZJOHsA6gGm7t4lGig04uoc7Wgza/Tjahmq9aaxUZ9iBY2BFO7vRmVLChmw5ouZ
    KrPADKVe9Ndilrc5KcqxCop4hQLtFZ9TC20jqIAs2xGYoOH2Z9POfuyeijvt1J5M
    F90nxZ14QuFtAoIBABG/6kbd47Gv6dqhC08wwIlQnGkRg4KxovUZn0ZbO6+ssAtu
    UNy3ssA6cL5zi/DwqOnxoUnQhV5J2Xy5DXnBeAV0Q+PSrpabb4VJrr/qId/pmsGu
    k9thS6MKZn2Ysfo55/xn6Zybm3wEPiaCmzz3cKjlCbQL99fUYqqGE34kvuofWejl
    hBCZiTmL98cTgEITTlK1MNEv8D94tzjfCC3HpjS2czy8lCuwD3nF9Dzp9W2Z7db1
    sDZtVEAFhZ3JN4M1Ks/hPNQJRceMTbb193VQeM944T8fkbNFz2oyU5kqwP89Lvw5
    oBLxMnKHv3PWNkuJqvMV+sRfoUAhOCZiyOWDMtECggEAbzf2a68D+jt0jVJ82f4q
    8KTPbrLEjJlqZOXzQzACcRlWDqqOOZItT+HiTlYR0hKagXzPe0bkEv5TQHwsMabS
    yaF82YJjs7C/buI6NZxFFlyD1Di9wOI42WlXxB+aN55BvXzBXfnIJcaFoRlgT4EP
    F1uptQAd9VABd5kQh6WuVAL0withkquJebKnsBOYadktI6oaMA2eITOcf/OnOg6e
    BY2IMvO9mVLuf8v3sHP036ETnAUpxNHDTe1/zEy/8XVyPZUjy5Vfn5audMwDYmxo
    0biYjZ9SKDH8BseC2sA5KlMuQvcHjtoG6rlCVcxZQZK+06QkIvCH1IE4sZ9ymUeS
    HQKCAQBsb4c8nKFC7LJYgmXukc6GhIyHsitfTJLWPmRyf0CmUrNB68DTzG+QPWgJ
    AngWETZeNZuHn8JFzRLM0Lr/jDHx30T3wrC4w/n7CeT5frSwmQmyY87ONZZnZMQj
    ytkhsfFBMEyfdZexQt4gokP09ImQ0zG04UxymliIgDOGErOSKkzwNdxDqovPp6WA
    c418xJ4nnI+cDMiHleHvjWfTxNYEL+fMYghh+c6/X4urKoA2EA36lhLtBXZmsqWO
    B0ZcMskQeH+TevUIOZNVxMgcvHilvjNUCzoxpTocKM8kvmK4mVKZxgvKInSkuWDV
    LKeqkgPsKBgPDX+GwUcUBgj3s/ju
    -----END PRIVATE KEY-----
