releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.16.1
    values:
      - ./cert-manager.yaml.gotmpl
      - fullnameOverride: cert-manager
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["apply", "-f", "issuer-ca.yaml"]
