# 1. Generate a private key:
# $> openssl genrsa -out core/cert-manager/ca/tls.key 2048
# 2. Generate a certificate:
# $> openssl req -x509 -nodes -new -sha256 -days 365 \
#     -key core/cert-manager/ca/tls.key \
#     -extensions v3_ca
#     -out core/cert-manager/ca/tls.crt \
#     -config core/cert-manager/openssl.cnf
apiVersion: v1
kind: Secret
metadata:
  name: fabricator.local-ca
data:
  tls.crt: '{{ readFile "ca/tls.crt" | b64enc }}'
  tls.key: '{{ readFile "ca/tls.key" | b64enc }}'
type: Opaque
