repositories:
  - name: bitnami
    url:  https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: cloudflared
    url: https://cloudflare.github.io/helm-charts

helmDefaults:
  wait: true
  force: true
  verify: true
  createNamespace: true
  timeout: 600

helmfiles:
  - path: cert-manager/helmfile.yaml
  # - path: sealed-secrets/helmfile.yaml
  - path: external-secrets/helmfile.yaml
  - path: cilium/helmfile.yaml
  - path: cloudflared/helmfile.yaml
  # - path: metallb/helmfile.yaml
  - path: nginx-ingress-controller/helmfile.yaml
  - path: argo/helmfile.yaml
