repositories:
  - name: bitnami
    url:  https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

helmDefaults:
  wait: true
  force: true
  verify: true
  createNamespace: true
  timeout: 600

helmfiles:
  - path: argo-cd/helmfile.yaml
  - path: nginx-ingress-controller/helmfile.yaml
  - path: sealed-secrets/helmfile.yaml
  - path: cert-manager/helmfile.yaml
  - path: cilium/helmfile.yaml
  - path: metallb/helmfile.yaml
