apiVersion: v2
appVersion: 1.0.0
description: A helm chart for garage deployed through argocd
maintainers:
- name: Do Ngoc Son
  email: dongocson.work@gmail.com
name: garage
version: 1.0.0
dependencies:
  - name: garage
    version: 0.7.1
