filesystem:
  s3a:
    enabled: true
    endpoint: http://minio.dwh-storage:9000

    accessKey: admin
    secretKey: Teko@123

    buckets:
      first:
        endpoint: https://asia.aws.amazon.com
        credentialsProvider: com.amazonaws.auth.EnvironmentVariableCredentialsProvider

      second:
        credentialsProvider: org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider
        accessKey: guest
        secretKey: foobar
        sessionToken: temporary
