image:
  repository: hub.teko.vn/dataops/hive
  tag: 3.1.3

commons:
  env:
    # Hive server2/metastore/client heap size in Mb
    - name: HADOOP_HEAPSIZE
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
