code-server:
  replicaCount: 1

  image:
    repository: codercom/code-server
    tag: 4.96.4
    pullPolicy: IfNotPresent

  existingSecret: "code-server-secret"

  serviceAccount:
    create: true

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false

  resources: {}

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi

  extraSecretMounts:
    - name: code-server-ssh
      mountPath: /tmp
      secretName: code-server-ssh
      readOnly: false

  volumePermissions:
    enabled: false

  extraInitContainers: |
    - name: setup-fabricator-project
      image: codercom/code-server:4.96.4
      pullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          if [ ! -d /home/coder/.ssh ]; then
            mkdir -p /home/coder/.ssh
            cp /tmp/id_ed25519 /home/coder/.ssh
            cp /tmp/id_ed25519.pub /home/coder/.ssh
            chmod 700 /home/coder/.ssh
            chmod 600 /home/coder/.ssh/id_ed25519
            chmod 644 /home/coder/.ssh/id_ed25519.pub
            ssh-keyscan github.com >> /home/coder/.ssh/known_hosts
            chown -R coder:coder /home/coder
          fi
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: data
          mountPath: /home/coder
          readOnly: false
        - name: code-server-ssh
          mountPath: /tmp
          secretName: code-server-ssh
          readOnly: true
