code-server:
  replicaCount: 1

  image:
    repository: codercom/code-server
    tag: 4.96.4
    pullPolicy: IfNotPresent

  existingSecret: "code-server-secret"

  serviceAccount:
    create: true

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false

  resources: {}

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi

  extraSecretMounts:
    - name: code-server-ssh
      mountPath: /home/coder/.ssh
      subPath: id_ed25519
      secretName: code-server-secret-files
      readOnly: true
    - name: code-server-ssh
      mountPath: /home/coder/.ssh
      subPath: id_ed25519.pub
      secretName: code-server-secret-files
      readOnly: true

  extraInitContainers:
    - name: setup-fabricator-project
      image: codercom/code-server:4.96.4
      pullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          ssh-keyscan github.com >> ./known_hosts
          git clone git@github.com:sondn98/fabricator.git
      volumeMounts:
        - name: data
          mountPath: /home/coder
