apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
  name: sealed-secrets-key
  namespace: sealed-secrets
data:
  tls.crt: '{{ readFile "key/tls.crt" | b64enc }}'
  tls.key: '{{ readFile "key/tls.key" | b64enc }}'

