metrics-server:
  image:
    registry: docker.io
    repository: bitnami/metrics-server
    tag: 0.7.2-debian-12-r3

  replicas: 1
  args:
    - --kubelet-insecure-tls
    - --secure-port=8443
    - --metric-resolution=40s

  apiService:
    create: false

  containerPorts:
    https: 8443

  service:
    type: ClusterIP
    ports:
      https: 443

  ## Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
  resourcesPreset: "none"
  resources: {}
