{
 "title": "Hardware",
 "tags": [ "linux" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Throttle cooling device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_cooling_device_cur_state{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Current {{ name }} in {{ type }}"
    },
    {
     "expr": "node_cooling_device_max_state{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max {{ name }} in {{ type }}"
    }
   ]
  },
  {
   "title": "Power supply",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_power_supply_online{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ power_supply }} online"
    }
   ]
  }
 ]
}