apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-auth-secret
  namespace: argo
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: redis-password
      remoteRef:
        key: "a58961e2-62c0-4069-bb97-b259011ba1ec"
