apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    redis-password: AgBftcOFsn62qpoWyGzkADjkJfE+G2CxLJutBSiR9tffBkW4ZaKwrqvNYuOsVxt7GAPfmhp4ORoisuWi107yu5Hb5eh9ntOdRZjCet1rwaE0BefCpljxRXU0eyRAwVDCTv+hTEjnPj7rdoqKyZl9Uzz/Yat3v6tZBNQosTobI4y8XxGd8MgA7jB1lHHPwFoluQJrb0clLodjC2bwHsWubyZ7sJWOEkbyiKxBmW3M8musaYVC0I07TivGXxzK591PKZUNlq0ZegpD9ZHAW0ufsBSCqZ6L3hiNCwil7R/F1tH65+tTiEkFmlt6t2daXzLomdperMB4hTSp/VSiCQQscAP0J9gCzRogDBiRQ308HAQUYIayMPEglPjvf8ehKkig9y+WncP8bPA+Kybg8gdSyc70Cfuca6KL+HpTBhhQji87yD2c3a0+t9eN5u8whnnEHIQBEpzaCwIXkCN0X4az13nBPgb2CnnloxqHXlMNrnZqGra3ItH/9bFn50JIvUSStDxXW/mohI1BbVgyqyY+kDRZtWhSx7pXOs+38oUYIYLqE09XYLL37up+hXO08rabPS6tkLZVQoPVrDu6ffPbCqdbOjo7XuohG1SHNHAQzJTcWAy6+T624qSe7DEwoqe56HPhxe4p/xk0kPXxJ/R1WEjlFEXJ8xXwAle3fFInOujxzZDDcerBn/rM72dg062HPYPw9Y/rWBvGdavANQ==
  template:
    type: Opaque
