apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password-secret
spec:
  refreshInterval: 1h
  target:
    name: redis-password-secret
  data:
  - secretKey: redis-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 06b2cfa1-a604-40b4-b013-b2bc010b5fb7
      version: v1
