apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: redis-password-secret
  data:
  - secretKey: redis-password
    remoteRef:
      key: /databases/postgresql/redis-password-secret/redis-password
      version: v1
