apiVersion: v2
appVersion: 1.0.0
description: A helm chart for elasticsearch deployed through argocd
maintainers:
- name: Do Ngoc Son
  email: dongocson.work@gmail.com
name: elasticsearch
version: 1.0.0
dependencies:
  - name: elasticsearch
    version: 21.3.16
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: kibana
    version: 11.2.20
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kibana.enabled
