apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.fabricator.secretStore }}
    kind: ClusterSecretStore
  target:
    name: code-server-secret
  data:
  - secretKey: password
    remoteRef:
      key: /others/code-server/code-server-secret/code-server-password
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-ssh
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.fabricator.secretStore }}
    kind: ClusterSecretStore
  target:
    name: code-server-ssh
  data:
  - secretKey: id_ed25519
    remoteRef:
      key: /others/code-server/code-server-ssh/code-server-sshkey
      version: v1
  - secretKey: id_ed25519.pub
    remoteRef:
      key: /others/code-server/code-server-ssh/code-server-sshkey-pub
      version: v1
