apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-secret
spec:
  refreshInterval: 1h
  target:
    name: code-server-secret
  data:
  - secretKey: password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: ed2626b7-2404-4c4a-8e30-b2bc010b8038
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-ssh
spec:
  refreshInterval: 1h
  target:
    name: code-server-ssh
  data:
  - secretKey: id_ed25519
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 937ec535-6b48-4fcf-9895-b2bc0113a04a
      version: v1
  - secretKey: id_ed25519.pub
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: e8e75574-0b80-4502-81da-b2bc0113c6fa
      version: v1
