apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensearch-admin-secret
spec:
  refreshInterval: 1h
  target:
    name: opensearch-admin-secret
  data:
  - secretKey: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 5fd270df-29ae-442b-a201-b449011c6ec4
      version: v1
