apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3
spec:
  refreshInterval: 1h
  target:
    name: seaweedfs-s3
  data:
  - secretKey: seaweedfs_s3_config
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 4897f016-456f-4521-a963-b44c007b58e8
      version: v1
      
