{{- $trino := .Values.trino | deepCopy }}
{{- $jvm   := index $trino "jvm.config" }}

{{- if .Values.metrics.enabled }}
  {{- $jvm = print ($jvm | trim) "\n-javaagent:/jmx-exporter/jmx_prometheus_javaagent.jar=" .Values.metrics.port ":/jmx-exporter/trino-metrics.yaml" }}
{{- end }}
{{- $trino := omit $trino "config.properties" "jvm.config" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.fullname" . }}-properties
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  jvm.config: |
    {{- $jvm | nindent 4 }}
{{- range $file, $content := $trino }}
  {{ $file }}: |
{{- if kindIs "map" $content }}
  {{- $_ := include "dict-cleanup" $content }}
    {{- range $key, $value := $content }}
    {{ $key }}={{ $value }}
    {{- end }}
{{- else if kindIs "slice" $content }}
    {{- range $option := $content }}
    {{ $option }}
    {{- end }}
{{- else if $content }}
    {{- $content | nindent 4 }}
{{- end }}
{{- end }}
