---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.fullname" . }}-scripts
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  mkcachedir.sh: |
    {{- tpl (.Files.Get "files/mkcachedir.sh") . | nindent 4 }}
