mysql:
  image:
    registry: docker.io
    repository: bitnami/mysql
    tag: 8.4.2-debian-12-r4

  architecture: standalone

  auth:
    createDatabase: true
    database: mysql_db
    username: admin
    replicationUser: replicator
    existingSecret: mysql-auth-secret

  primary:
    name: primary
    resources: {}
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi

    service:
      type: ClusterIP
      ports:
        mysql: 3306

    pdb:
      create: true

  serviceAccount:
    create: true

  rbac:
    create: true

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/mysqld-exporter
      tag: 0.17.2-debian-12-r2
    containerPorts:
      http: 9104
    service:
      type: ClusterIP
      port: 9104
    extraArgs:
      primary: []
        # - --collect.auto_increment.columns
        # - --collect.binlog_size
        # - --collect.engine_innodb_status
        # - --collect.engine_tokudb_status
        # - --collect.global_status
        # - --collect.global_variables
        # - --collect.info_schema.clientstats
        # - --collect.info_schema.innodb_metrics
        # - --collect.info_schema.innodb_tablespaces
        # - --collect.info_schema.innodb_cmp
        # - --collect.info_schema.innodb_cmpmem
        # - --collect.info_schema.processlist
        # - --collect.info_schema.processlist.min_time
        # - --collect.info_schema.query_response_time
        # - --collect.info_schema.tables
        # - --collect.info_schema.tables.databases
        # - --collect.info_schema.tablestats
        # - --collect.info_schema.userstats
        # - --collect.perf_schema.eventsstatements
        # - --collect.perf_schema.eventsstatements.digest_text_limit
        # - --collect.perf_schema.eventsstatements.limit
        # - --collect.perf_schema.eventsstatements.timelimit
        # - --collect.perf_schema.eventswaits
        # - --collect.perf_schema.file_events
        # - --collect.perf_schema.file_instances
        # - --collect.perf_schema.indexiowaits
        # - --collect.perf_schema.tableiowaits
        # - --collect.perf_schema.tablelocks
        # - --collect.perf_schema.replication_group_member_stats
        # - --collect.slave_status
        # - --collect.slave_hosts
        # - --collect.heartbeat
        # - --collect.heartbeat.database
        # - --collect.heartbeat.table
    resourcesPreset: "none"
    resources: {}
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      interval: 30s
      scrapeTimeout: 30s
      honorLabels: true
