{{- if and .Values.userlist (not .Values.existingUserlistSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.usersSecretName" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: |-
    {{- range $key, $value := .Values.userlist }}
    {{ $key | quote }} {{ $value | quote }}
    {{- end }}
{{- end }}
