apiVersion: v2
appVersion: 1.0.0
description: A helm chart for Argo Workflow deployed through argocd
maintainers:
- name: Do Ngoc Son
  email: dongocson.work@gmail.com
name: argo-workflows
version: 1.0.0
dependencies:
  - name: argo-workflows
    version: 11.1.11
    repository: oci://registry-1.docker.io/bitnamicharts
