opensearch:
  clusterName: "opensearch-cluster"
  nodeGroup: "master"

  singleNode: true
  masterService: "opensearch-cluster-master"

  roles:
    - master
    - ingest
    - data
    - remote_cluster_client

  opensearchHome: /usr/share/opensearch

  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      network.host: 0.0.0.0

  envFrom:
    - secretRef:
        name: opensearch-admin-secret

  image:
    repository: "opensearchproject/opensearch"
    # override image tag, which is .Chart.AppVersion by default
    tag: "3.6.0"

  opensearchJavaOpts: "-Xmx2g -Xms2g"

  resources: {}
  networkHost: "0.0.0.0"

  persistence:
    enabled: true
    enableInitChown: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  antiAffinityTopologyKey: "kubernetes.io/hostname"
  antiAffinity: "soft"
  enableServiceLinks: true

  protocol: https
  httpPort: 9200
  transportPort: 9300
  metricsPort: 9600
  httpHostPort: ""
  transportHostPort: ""

  service:
    type: ClusterIP
    httpPortName: http
    transportPortName: transport
    metricsPortName: metrics
    
  maxUnavailable: 1
  terminationGracePeriod: 120
  sysctlVmMaxMapCount: 262144

opensearchDashboards:
  enabled: <Injected in runtime>
  # Copyright OpenSearch Contributors
  # SPDX-License-Identifier: Apache-2.0

  # Default values for opensearch-dashboards.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  opensearchHosts: "https://opensearch-cluster-master:9200"
  replicaCount: 1

  image:
    repository: "opensearchproject/opensearch-dashboards"
    tag: "3.6.0"

  serviceAccount:
    create: true
  rbac:
    create: true

  serverHost: "0.0.0.0"

  service:
    type: ClusterIP
    port: 5601
    metricsPort: 9601
    httpPortName: http
    metricsPortName: metrics

  resources: {}
