version: '3'

silent: true

dotenv:
  - ../.env

vars:
  INVENTORIES: '{{ .INVENTORIES | default "bare-metal.yml" }}'

tasks:
  provision:
    cmds:
      - ansible-playbook -i inventories/{{ .INVENTORIES }} playbook.yml
