unichart:
  applicationName: jarvis

  deployment:
    image:
      repository: docker.io/sondn1/jarvis
      tag: v0.3.1

    ports:
      - containerPort: 8000
        name: http
        protocol: TCP
    resources: {}
    env:
      OLLAMA_BASE_URL:
        value: http://ollama.ollama.svc:11434
      DEFAULT_MODEL:
        value: gemma3:1b
      ENABLE_AGENT_ORCHESTRATION: 
        value: 'True'

  service:
    ports:
      - port: 8000
        name: http
        protocol: TCP
        targetPort: 8000

  rbac:
    enabled: true
    serviceAccount:
      enabled: true
