{{- $coreSite := index .Values.hadoopConfig "core-site.xml" }}

{{- if .Values.filesystem.s3a.enabled }}
  {{- $s3a   := .Values.filesystem.s3a }}
  {{- $props := include "hive.filesystem.s3a" (list "" $s3a) | fromYaml }}
  {{- $_ := mergeOverwrite $coreSite $props }}

  {{- range $bucketName, $bucketProps := $s3a.buckets }}
    {{- $props := include "hive.filesystem.s3a" (list $bucketName $bucketProps) | fromYaml }}
    {{- $_ := mergeOverwrite $coreSite $props }}
  {{- end }}
{{- end }}

{{- if .Values.filesystem.gs.enabled }}
  {{- $gs := .Values.filesystem.gs }}
  {{- $props := include "hive.filesystem.gs" $gs | fromYaml }}
  {{- $_ := mergeOverwrite $coreSite $props }}
{{- end }}

{{- if .Values.filesystem.wasb.enabled }}
  {{- $wasb := .Values.filesystem.wasb }}
  {{- range $accountName, $accessKey := $wasb.accounts }}
    {{- $_ := set $coreSite (printf "fs.azure.account.key.%s.blob.core.windows.net" $accountName) $accessKey }}
  {{- end }}
{{- end }}

{{- if .Values.filesystem.adl.enabled }}
  {{- $adl   := .Values.filesystem.adl }}
  {{- $props := include "hive.filesystem.adl" (list "" $adl) | fromYaml }}
  {{- $_ := mergeOverwrite $coreSite $props }}

  {{- range $accName, $accProps := $adl.accounts }}
    {{- $props := include "hive.filesystem.adl" (list $accName $accProps) | fromYaml }}
    {{- $_ := mergeOverwrite $coreSite $props }}
  {{- end }}
{{- end }}

{{- if .Values.filesystem.swift.enabled }}
  {{- $swift := .Values.filesystem.swift }}

  {{- range $serviceName, $serviceProps := $swift.services }}
    {{- $props := include "hive.filesystem.swift" (list $serviceName $serviceProps) | fromYaml }}
    {{- $_ := mergeOverwrite $coreSite $props }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}-hadoop-config
  labels:
    {{- include "hive.labels" . | nindent 4 }}
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
    {{- range $name, $value := $coreSite }}
      <property>
        <name>{{ $name }}</name>
        {{- if toString $value | contains "\n" }}
        <value>
          {{- $value | trim | nindent 10 }}
        </value>
        {{- else }}
        <value>{{ $value }}</value>
        {{- end }}
      </property>
    {{ end }}
    </configuration>
