apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.fabricator.secretStore }}
    kind: ClusterSecretStore
  target:
    name: clickhouse-auth-secret
  data:
  - secretKey: clickhouse-password
    remoteRef:
      key: /warehouse/keycloak/clickhouse-auth-secret/clickhouse-password
      version: v1
