apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-auth-secret
  namespace: clickhouse
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    clickhouse-password: AgBfs92XSy1R4aGZ1jrE0wpZc0j4QcSgAN29iMLkkayibABpm1l1QSotQWE5q9GK4YSlH/SZI3KkRD1XBlYFwssHvzx9lAQhnX773M9zL112azgq2r7sMZZRXQtgMM2KBL8DMdeIAJ5O0zbsgDIlgx+ZVrodCGzkGJaRRN/6Su/9n285/FhE4vhD6ror2mTaalTfUDJjClSc7oKaalym+PTzNK5NqmlS3wQyokynHKNwLsWn8fQs81qq9F198Js+4oYNaPBaItuAYDqZelpRYFfs96eNMzTmkO/58UtS3zkgluPUq1MqI7F0J/Ofcz1M9JUy4faAMDTe3igCGNSVxkbghOMO/uiFybgdtQTchBvjEpH4h0CVIcQes5omAVPu6fCUWiL1+a9Q5saqa1gznW/UFMp+0E0RwT8z7T1EwzUbPgYlXmJNvnSlx/6IvAjkuBkjKxKRP2Nuu+fcURgu3sATSAPNMXdIwZwx0q/Mzwp2CThV4WUft0RkJXZ7ww2B5Ppm2WlK+aufSAYKB//9z5xCtlIuhuYDC/WsruHLCY9kUfxd2oBLN/t3Bj+E7og6e1BuZgtxskVfavdjYJZVt6KcOCxYuDvdiW1A8BCOVAr727+NaUOkFQAs28+48jQBCOsrJo8YGTKTxErBpA1q1fL98VOOAhLtk5+AzTghPRBNPIPfHNAKdt0cDxnMznMJsrIe4OEjljmS4goa+Q==
  template:
    type: Opaque
