apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: clickhouse-auth-secret
  data:
  - secretKey: clickhouse-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 627dda3f-20d8-44de-8b2e-b2bc010c4416
      version: v1
