grafana:
  image:
    registry: docker.io
    repository: bitnami/grafana
    tag: 11.2.0-debian-12-r3

  admin:
    user: grafana
    existingSecret: grafana-auth-secret
    existingSecretPasswordKey: grafana-password

  plugins: "grafana-oncall-app"

  dashboardsConfigMaps: []

  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
      - name: Prometheus/Metrics
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc:9090
        isDefault: true

  grafana:
    replicaCount: 1
    containerPorts:
      grafana: 3000
    ## Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
    resourcesPreset: "none"
    resources: {}

  dashboardsProvider:
    enabled: true
    configMapName: "grafana-dashboard-provider"
  dashboardsConfigMaps:
    - configMapName: dashboards-k8s-api-server
      folderName: Kubernetes
      fileName: api_server.json
    - configMapName: dashboards-k8s-view-global
      folderName: Kubernetes
      fileName: view_global.json
    - configMapName: dashboards-k8s-view-namespaces
      folderName: Kubernetes
      fileName: view_namespaces.json
    - configMapName: dashboards-k8s-view-nodes
      folderName: Kubernetes
      fileName: view_nodes.json
    - configMapName: dashboards-k8s-view-pods
      folderName: Kubernetes
      fileName: view_pods.json

    - configMapName: dashboards-nodes-hardware
      folderName: Nodes
      fileName: hardware.json
    - configMapName: dashboards-nodes-network
      folderName: Nodes
      fileName: network.json
    - configMapName: dashboards-nodes-resources
      folderName: Nodes
      fileName: resources.json
    - configMapName: dashboards-nodes-storage
      folderName: Nodes
      fileName: storage.json
    - configMapName: dashboards-nodes-system
      folderName: Nodes
      fileName: system.json

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

  service:
    type: ClusterIP
    ports:
      grafana: 3000

  ingress:
    # Use cloudflare tunnel instead
    enabled: false

  metrics:
    enabled: false

