grafana:
  image:
    registry: docker.io
    repository: bitnami/grafana
    tag: 11.2.0-debian-12-r3

  admin:
    user: grafana
    existingSecret: grafana-auth-secret
    existingSecretPasswordKey: grafana-password

  plugins: ""

  dashboardsConfigMaps: []

  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
      - name: Prometheus/Metrics
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc:9090
        isDefault: true

  grafana:
    replicaCount: 1
    containerPorts:
      grafana: 3000
    ## Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
    resourcesPreset: "none"
    resources: {}

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

  service:
    type: ClusterIP
    ports:
      grafana: 3000

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    hostname: grafana.fabricator.vn
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

  metrics:
    enabled: false

