apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: openclaw
data:
  AGENTS.md: |-
    {{- .Files.Get "files/AGENTS.md" | nindent 4 }}
  SOUL.md: |-
    {{- .Files.Get "files/SOUL.md" | nindent 4 }}
  TOOLS.md: |-
    {{- .Files.Get "files/TOOLS.md" | nindent 4 }}
  IDENTITY.md: |-
    {{- .Files.Get "files/IDENTITY.md" | nindent 4 }}
  HEARTBEAT.md: |-
    {{- .Files.Get "files/HEARTBEAT.md" | nindent 4 }}
  USER.md: |-
    {{- .Files.Get "files/USER.md" | nindent 4 }}
  openclaw.json: |-
    {{- .Files.Get "files/openclaw.json" | nindent 4 }}
