apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openclaw-secret
spec:
  refreshInterval: 1h
  target:
    name: openclaw-secret
  data:
  - secretKey: ANTHROPIC_API_KEY
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 4a9c34fb-3cdb-4eea-a2f3-b47d00daf218
      version: v1
  - secretKey: OPENCLAW_GATEWAY_TOKEN
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 09d254ff-3ce5-4a98-a23a-b47d00db1869
      version: v1
      