version: '3'

silent: true

tasks:

  up:
    cmds:
      - vagrant up

  down:
    cmds:
      - vagrant halt

  status:
    cmds:
      - vagrant status

  delete:
    cmds:
      - vagrant destroy -f
