Vagrant.configure("2") do |config|

  master = { name: "homelab-1", ip: "192.168.56.10" }

  workers = [
    { name: "homelab-2", ip: "192.168.56.11" },
    { name: "homelab-3", ip: "192.168.56.12" }
  ]

  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  ## Define Master node
  config.vm.define master[:name] do |master_node|
    master_node.vm.box = "ubuntu/jammy64"
    master_node.vm.hostname = master[:name]
    master_node.vm.network "private_network", ip: master[:ip]
    master_node.vm.provider "virtualbox" do |vb|
      vb.name = master[:name]
      vb.gui = false
      vb.memory = ENV['K3S_SERVER_MEMORY'] || "2048"
      vb.cpus = ENV['K3S_SERVER_CPUS'] || 1
    end
  end

  # Define Worker nodes
  workers.each do |worker_node|
    config.vm.define worker_node[:name] do |worker|
      worker.vm.box = "ubuntu/jammy64"
      worker.vm.hostname = worker_node[:name]
      worker.vm.network "private_network", ip: worker_node[:ip]
      worker.vm.provider "virtualbox" do |vb|
        vb.name = worker_node[:name]
        vb.gui = false
        vb.memory = ENV['K3S_AGENT_MEMORY'] || "4096"
        vb.cpus = ENV['K3S_AGENT_CPUS'] || 1
      end
    end
  end
end
