apiVersion: v2
appVersion: 1.0.0
description: A helm chart for Onyx deployed through argocd
maintainers:
- name: Do Ngoc Son
  email: dongocson.work@gmail.com
name: onyx
version: 1.0.0
dependencies:
  - name: onyx
    version: 0.4.48
    repository: https://onyx-dot-app.github.io/onyx/
