apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-auth-secret
spec:
  refreshInterval: 1h
  target:
    name: airflow-auth-secret
  data:
  - secretKey: airflow-fernet-key
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 7cf34430-ba4f-4e95-8392-b2bc01094604
      version: v1
  - secretKey: airflow-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 5ffb21e3-e820-441b-9e46-b2bc01096740
      version: v1
  - secretKey: airflow-secret-key
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: c404fe9e-e413-4be1-a514-b2bc01098a14
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-pg-secret
spec:
  refreshInterval: 1h
  target:
    name: airflow-pg-secret
  data:
  - secretKey: airflow-pg-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 5cedba16-5f6a-4de7-808a-b2bc01099faa
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-redis-secret
spec:
  refreshInterval: 1h
  target:
    name: airflow-redis-secret
  data:
  - secretKey: redis-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 3f0722c5-2de6-446f-994c-b2bc0109b572
      version: v1
