apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-auth-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    airflow-fernet-key: AgBZny8QAKKtBphAaU3SW/xR3cxZn1qhDN8eG/ME3OD+5AgWdXRJadz8JTbDazJJOJ7XkEPf38uPDeCNiy7HQ56UmAJ2kcS3PBk2AqgX0r7CRAGL1TrKIUUbakC44jXe/UFmhHdFTzEwpZMX/3b/Q+9Bzu0CxFSxx3HBGB+li0T5TKDyUWNi/3HynJPRLkNgSp1+9D0JyE3g8yfIPjLWVXrnx3jSQPMWHy/8Sg1MyuKTc3odrwEld2F2Ty9g84rBfJXifsLdXYV7jMuR6kZ16Fhau6E5L5OuWOT2Xz7dIWrrqEEtvXQrvZhOBKjXuEaMewpbNZyz+XP5uk7nMXO9u3c+w6s1daHK7aKT5LXFVgWko81rT1AAGIdN3DIf0dc5coSelqs//8kQV7Wi8CHyyuF+EXLwlqfvQ2bWPzGr45VGWKZGjKer5LCvXjm6kJ5HMb5jXd6xP+k3S1aeVK67QQiAW2/wRC76/go3HaFWk+2CNO/l5kKbaCbYLhrDVcNZ2tqYBQPMATuPVjmt0rGT8QMgf3OZTZlW7+1+GERl8wXXGjp4ude9/+YdyJxIOB5Iszbb+DkoD/YdRVkWGNkazoxN9AK1IJ87ZxoP9k8oxM/DF7nhwRTZP40D9FuI6IraLUR+oyjL4dwuzwUkTU5NGhRPxFRrFsFJ1GLl16YhEv7yemp9ByY6snV5Qg7I5YV7HkP11pVjd+jQGf+mH+k3W6q5YLI=
    airflow-password: AgASKUgFrxPHUgUAWIVbtdi/AdhL2sAWEdyCDyLR86kOJvjG17lZWpaEaZ3XYm4RlWZMg0ZnLFos00RiRW+gb9pBYY7xD35tNQHWWheUibJUNpb3E1ccQtxX7Q0e3nQRszMaSv2TL4GN3fqQFQrv/Er2Fd9AAAqqxfh2oAkK/fAURzY8XsiEH3RodTk/khPPqjabq9lKUe8rGQ06okiia0Q8AKGIyNfE9vMu0Pf1gtFX/O/AqMeyUgMyfdhNMf+1OCCwMJllqr6I3B0X8E1gz6bpBdvnaY6uFaktNN9J+nzrKKn28RyQda2k1wPqQ13JxP4VCnN8NGz3MwawNIXNkiKmnxHHMRgtBTSLGegnbZ8oYsT6i/eIsVRSLISISo+sFQzVnFDGL4CYTnqPRSuO59eUSkw4sgNmBdUkk7cGm3apcfqVpbAC1SlTjmuydDz6gY1U7RVbFAoYOTNA7JXWAYfQtgUeDOAKGg9lgfGn3kNA3WOZjdkn1NoI6j/LW/F0gXX3i30GRd1dZ1VLb0Ht1s4XRsD7i+jE/lJaQr+L+KvTas5XczEjHjd7M8Zg/pazTSGbFiXfben20QoFUeGJcExKuuIKtrhIEet8o9DqSwoSol/m6Q3NNd9e0gOj+Ub/OWtLepnw5B2epR1PbqSQX8tSnH8cqhH/cVCUlX3eCoHFGkwsTO4znG4wJrMxWVTIWTOdeaI+8bjcLfHf3g==
    airflow-secret-key: AgAXtWJnlDseWSARVz9JO05v/TN33D3kOa5ixQwjy1H4pbQo/LL81s0+SS8NYv0K/ukwX4SVkeZ7iY4VxbE8JthcXq1hHZ1KpSeMZQEUZlaWrMDBPFlYKLT5jSF5RCOtlJRn8fwCxPAPdt7D6t5vYdifLI25bPUA9S5pH688vQtxDYqGuWXbuwauFLb0bpKHiCCNftpLiu+oBIG5CYg34cdN6QAoAxZgelIN5MtlDKkS2OFqHRS0TleQVhG29pDLudMlnWirrjaQvOiV517oN1XHZo5dz7nUy3LOdmb34q+NEYAmD1MrHt1Be5btKZsYmV3R5oWENLLs1gajA4zTg969fkfKrpCazpGKv4VR9reKnDMaG2DYysfI2a5WHykuKdkmTuX33s02cIGiZE1JEqMYrQAgE6kXGVyqMhLn7tz1CqvxqaYSMxbYMEZWAWQeZra+nMaPDgLzZF5J1ZHbn6s+zVXIc5CnTrMos/3V2YYgeBdSBwxYIdyiAVvZMiTPQjo7nZWl1QLyMXgR4Ge55ZKWYTjnLD8c4wFOAKhy/0m7pfIDcvaojPigzu9cDWh7lHw7YYCabfCbnPm9KEBssxc6lOw20SWPllghMc9TpaV9AjcQxHCGLL1rLXvnDXlUv8zJ50rgwUI3LbbIo/1+DCxkAMMvfFS1e/QzFnNtxDQH17vPBQJ8hkGdXdVWxJ+HLBHgzOUajOP9bz3VG/90gt53iUY=
  template:
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-pg-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    airflow-pg-password: AgAdBWxiLJuLkrO0TBovdlT1iPHWBBEaWebWazVVjpEWu7Vb0gbJB20edXO8iZ/6Bnf84Qa/vFd/q18mOgWbzlJ7YwaVidLYKPOY/aOXLlhTH3EMfm/lVVNOr2yseKunX30Y2ffuWtjyDSgTnq5JMO5HRDvW77FC/zJrXptH9brTraw9uT/oz3xcdZYqJ55jHA+HsVf/RPWUZOoEcAzY8zqcC1i/kzLUBIYkpvZDIq6xWj6wgkEQ4zkIYyd+A3Z69ijv0FZ8cEUIIXGPO+Ttm2TTxSA84UETXSpjwVLpM0R11Y87q599dFBRFuPqrT+20IUX22JagJbDwQzZ6HMfafgSLwcj/+Gbo1CooK5rIpiGL4v2gKc1E2CODrsmSZitKfJLAuA05n63Lj4Ks8NU6ZzyBVCw+1uWGdsBcUxvbYx81B2rlTsrqwOoh4e2iiI0SQkQp+4UeHj/FhuayykL3tr6YW252L7amlFe9LEo3TJOI8lH251tGSpKBIlgg43KnNCIADyOsVGu/4W5gg2TDWQGByLPaWoGvp/XefU1ru5jAByTqzaCON09XxN1/SOUJrMmJW51tljnlDZWkEYLyq1UbFulcoyUQfsGEWGFzYbNaXEYXowwvUNk+5/cvqcgTTRLCjiC1oTFpJrStekGTgiTJhCyHOe4iVFXDe8hieZ6aKKoygYPmUD9pe3yF9J0kmsTO3Uf6BMHQWqIbA==
  template:
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-redis-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    redis-password: AgAvHVLS7fhGXeB6hF34z+DcXqBw74UL8tMY0zv7tNkiEPtQ51pcr5zrZBWfZRfxGvweKBjXwRRbZ3xUBgBUfN+pNrWV5uqMrATvGnA41on6dFfhdMuSX9OgLfRh1R/ZDounIf2NkLl2yzgnSmtufVvlTCoHJ3vJlDGY1Pz7mh0z5RlQ2Jt28r5CsFY1tpAW2NnSlBBmljhQpJDYQ7aWCz8m6w6cztbqy2rej068fTLvRYFF19wW8xIr1b5eCjLZxlxuhCZwWEgbKaWGBY5ONgLMQlXizYUPuPipqqrrqjfBS1r9d9PnAfMXCMrEgo0YKs0swN+Y2kbsfqAaG97ME2Qb/Rtv2k8LS92QlN/wPwhwRHLBbw8/MM2AwYlmij9wE5wgBqriVEncpMXSOtV8YsHTLO17RUCP+ICvALWcwFbclIJp4MzfQ3l46F24QSJZ9wG5PPxvKqQsRDuJ5MvfYKhy5kRk7RVuenrbpLXY4Hh5g8tmH0W2tkLMH3NUxFgxlqF4QPOVadrHR2m8O/kCrWz9GuM9v+syyOLdgnbMw9WHifzWsy74za869GGZ+5mBS4Ofz+NmzGZuCh0GoaIoYoH2TXGtLOU8NsgDiOTuib3H4PrNA65gH7v9ZLmfTeu9FmhHy7DIZOlQPDsGn2w+oGKgmmiF9qaqQDdBcEAoda7o3Vdk2h6MVozzZPneGokO85oIYQjGNTXRTuJKrA==
  template:
    type: Opaque
