apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: airflow-auth-secret
  data:
  - secretKey: airflow-fernet-key
    remoteRef:
      key: /computation/airflow/airflow-auth-secret/airflow-fernet-key
      version: v1
  - secretKey: airflow-password
    remoteRef:
      key: /computation/airflow/airflow-auth-secret/airflow-password
      version: v1
  - secretKey: airflow-secret-key
    remoteRef:
      key: /computation/airflow/airflow-auth-secret/airflow-secret-key
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-pg-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: airflow-pg-secret
  data:
  - secretKey: airflow-pg-password
    remoteRef:
      key: /computation/airflow/airflow-pg-secret/airflow-pg-password
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-pg-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: airflow-redis-secret
  data:
  - secretKey: redis-password
    remoteRef:
      key: /computation/airflow/airflow-redis-secret/redis-password
      version: v1
