apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-github-secret
spec:
  refreshInterval: 1h
  target:
    name: arc-github-secret
  data:
  - secretKey: github_token
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 55bf0808-4c52-4209-b322-b40d011c0fc0
      version: v1
      