apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-pg-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    jupyterhub-pg-password: AgBF1jlKsT/K0qR+a9ZPdGFPWwOrJzOLAQWzrFp/1PxDnSOE73C7g+2Ay3H4+00ZcP40f+lMM8eEfwfHyvQDKXvTohrsrtoMSYAGIWXlCZf83VuWjnjW7ZoyP+VfslIa2CLgkD3dvGJS22ihz1LPXh2KLKD14saAh8xP7ghhI/6sAPOPi3Seq6uTRFGt+SMGYe9VOk7Sox95ibzmm+YaM0zyAV6Wljecel+6VXQWBDHoYZV8H4V58W4ZnJI4fFeX9CK5DmtnF3kp2mkubfWm5qEuxxlflVsqnlXpvvJpGVVjujCYlLcfB8x01QOSIkP7JOuB5rJMxAMWLWBbVBM9TbzmMsUboRCcHk4sZMiZ7hByIapqxzOOh2st/7LzMoT8uUB4y7KlSpSxMBCW0PoTGygwa9bGgpY58XsUEHDLhpHNMl0jfIoIbnwa22g4zpPLd/Nh4729SCfuuv9oIj0MkUtVF5+GKrvaaCbv+eQUJ9CyvH7g5Sg3Hkpt5Fa3m7+WEYQaXmSkp8kWNYuPkWhQTESsP9gYvzG33gaXXT2hgI0omOWld3fUoEYN4XEryXHpO1vALw4MPHTRXbCNC3Wmg/3WmYuRMT4fY/+HI9o9fhXfW+eBYut2Gw23t0mkizAl5GsbMl66Vw3cAAZqUJTRFHXqN7uryuNedL6f5d44m+DTjPzv2/xdjmmdd6N5FDRf9mFWhH+UJZ7kpBsa1g==
  template:
    type: Opaque
