apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jupyterhub-pg-secret
spec:
  refreshInterval: 1h
  target:
    name: jupyterhub-pg-secret
  data:
  - secretKey: jupyterhub-pg-password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 4501f9b4-98f4-409f-8229-b2bc0109c744
      version: v1
