apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jupyterhub-pg-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.fabricator.secretStore }}
    kind: ClusterSecretStore
  target:
    name: jupyterhub-pg-secret
  data:
  - secretKey: jupyterhub-pg-password
    remoteRef:
      key: /computation/jupyterhub/jupyterhub-pg-secret/jupyterhub-pg-password
      version: v1
