apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nifi-tls-keystore-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.fabricator.secretStore }}
    kind: ClusterSecretStore
  target:
    name: nifi-tls-keystore-secret
  data:
  - secretKey: password
    remoteRef:
      key: /computation/nifi/nifi-tls-keystore-secret/password
      version: v1
