apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nifi-tls-keystore-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    password: AgCymv9JkbVm2AvRSQl/E16Pj7m0YO+jT89jIFNIp1MpkRZ6AMHAL2QMxQwufeq8+sn+ZYgmD9bQ8WOFcxXip3ombCQnOlFguai8XAszXXxnNyzhXkgcDaI38z4x9xjnqiZxMuU0AlWlIc/B1h0EA716il0JQ//wgZqiKLoO2tUpnkP3zKRaF3LLSSnQNxEcLu8k6LR7tEadykYAE6qnAZJL4fw3s+Mhz8AWv7rreFhenWd2dAYaHKBOqKSSBCnInHH0QCtyCug7iK+54HsYcN0d7B7Pbp0orAy/eQDNsBZImTL7WrRNuF6C8MwygtfbbcSrx5AGUOTWMh8YD8FEFLwjY8IOG9WU03PfUDfgNZ8tmG3Jcho+3BDWDKE+V8Yfr6pWVhHhqvelIu7WV3qdTYi08aewnRRWSSHwzEV7fM7fhc1WFo/izIKD90Cr3Ck7vs3eXo5CjVwWqLASE6SRG+L/M8tvnppm0Gma4y+O6jQuVVXEL5ssHzJoeSOaf1OKI9N5mexWnBou36yLcGkSAj3gGU6RcoCyXguf13p9cC6qPaHvg09+pjFiI6e7p1cT1tAhCqOydrNTspEbE2hKa451I2E9XXI38h1b/OyShuVO+AGKUnUREmis1vCPnNuLa00eKqfm79OSs2r4GtmsIWIcswL6xVw6TwlrqFKYoSzUpxtT/DFcsUYNNU33lXPTsIT00C+VDbIYGN1P3g==
  template:
    type: Opaque
