apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nifi-tls-keystore-secret
spec:
  refreshInterval: 1h
  target:
    name: nifi-tls-keystore-secret
  data:
  - secretKey: password
    sourceRef:
      storeRef:
        name: bitwarden-secretsmanager
        kind: ClusterSecretStore
    remoteRef:
      key: 74660b40-919c-4836-b36a-b2bc0109dbdb
      version: v1
